### ISSUE TITLE
MFR.DSK & mfr.nextor-2.1.1.rom missing from repo?

### ISSUE THREAD

**Issue by zomgugoff** [vipoo/yellow-msx-series-for-rc2014#11]
The instructions for using the MegaFlashROM SCC+ SD mentions getting MFR.DSK and mfr.nextor-2.1.1.rom from the releases for this repo. I can't find any reference to those files. They're not in the msx-rc2014-24-02-09.zip file either. Were they removed?

**Comment by vipoo** [comment]
Hi mate,

I am very sorry, it does seem to have dropped off the build system.  For
me, its been a rather long time since I used the Mega Flash rom.

I just did a quick test, and the image I currently had installed in the
MegaFlashRom seems to work with the latest release flash into my main rom.

When I went to update the SD card image - yep --- I found '
*mfr.nextor-2.1.1.rom*' was missing.

Also, the instructions I think has a typo, when referring to *mfr.com
<http://mfr.com>* - I think it should be saying to rename '
*mfr.nextor-2.1.1.rom*' to *mfr.rom *when copying the SD card.

You will find if you download the release '22-03-13' you can copy the '
*mfr.nextor-2.1.1.rom*' and may at least get something working.  I have not
tested this yet - (only tested with whatever version was on my SD card)

I will look asap to my build process, and let you know as soon as I have it
fixed.

Dean.

**Comment by zomgugoff** [comment]
I have been able to access the cart using opfxsd and Sofarom, so it hasn't been completely unusable. But I haven't had any way to access the SD slots on the cart and the first 2 drive letters, as you note, have been inaccessible. I'll give the 2.1.1 version a shot and see what it does. Thanks!

**Comment by zomgugoff** [comment]
Well, it still works. But, USB storage's mapping is overridden by the ROM disk or just not being done at all.

A: is the cart ROM disk
B: is the first SD card(with only 1 card inserted)
C: is the main ROM disk
D: is the other ROM disk

I've been swapping command2.com and nextor.sys out to see what I can get. With a non-nextor msxdos2.sys in place of nextor.sys, the USB storage is getting a drive letter, but other things don't work without the real nextor.sys (like mapdrv). I'd like to not lose access to the low-memory command2.com with tab-completion. I just don't know how to mapdrv the USB storage - if that's possible.

**Comment by vipoo** [comment]
> I just don't know how to mapdrv the USB storage - if that's possible.

Not sure about this.  Stretching my knowledge.

`DRVINFO` will list the current mounted drives. 

IF you just type `MAPDRV` on its own, you will is command line options

In theory to add an existing drv mapping for a driver in the ROM disk - it might be something like

`MAPDRV F: 1 X-1 3-3`

where X is the specific device you want to load (the device number is dependant on what devices get discovered/loaded at boot time - eg embedded ROM disk,  compact flash, USB partitions)  

Really not sure.

In regards to the main issue, I am just about to push a change to the main Makefile to ensure the `mfr...*` files are created and packaged in the release

**Comment by zomgugoff** [comment]
I think I've been inadvertantly making an incosistant result. I forgot I was running at 20MHz (3 wait), so random things don't work right. I can replicate all drives appearing as they should at 3.5MHz.

I'll give that a rebuild later and give that a test. Thank you.

**Comment by vipoo** [comment]
Cool.  Yes the MFR is not compatible with the faster turbo CPU.

I have just made a recent commit, and done some initial testing.  you can pull and build yourself, or grab the required files from the latest builds' archive.

---
Every push I make will zip up all artifacts (roms, disk images, application etc). You can see them under the actions tab:
https://github.com/vipoo/yellow-msx-series-for-rc2014/actions
Just click into the latest completed build --  then scroll down and you will see the 'Artifacts' section with the relevant zip files.  

So unless you want to 'change' the code for any reason, you dont need to build on your machine.

**Comment by zomgugoff** [comment]
Ah, I didn't realize they would be pre-compiled on the repo. It's too bad about MFR not running at higher speeds. It seems to work ok at 7.4MHz and intermittently at 20MHz with 3 waits.

**Comment by vipoo** [comment]
Surprised you get the MFR to work at even 7.4Mhz - that double the clock speed of a standard MSX machine.

Are you ok if I close this issue?
