### ISSUE TITLE
Git recursive permission issue

### ISSUE THREAD

**Issue by zomgugoff** [vipoo/yellow-msx-series-for-rc2014#7]
Downloading submodules appears to be trying to downloading via SSH, which requires extra setup on the user's part. Can you change the URLs to use HTTPS?

**Comment by vipoo** [comment]
I can have a look, but I do personally prefer and would recommend using ssh keys to access github code.  

I think i had originally used https - but then that introduced issue for me when i commit/push. (authentication) - and I had to manually change the origin's of the submodules locally.

I assume you did something like that yourself - and change the submodules paths - then was able to pull all the code?

**Comment by zomgugoff** [comment]
I had to look up the HTTPS URLs and change them in the .gitmodules file. I'm not that experienced with Git, so the first time I did it, it continued to try using git@ URLs instead. I had to re-clone the repo, drop in the changed URLs, then run the submodule update. Everything downloaded normally after that

**Comment by vipoo** [comment]
Cool - when i get a chance, I will document this procedure - to make it easier for those with keys established.

Thanks

**Comment by zomgugoff** [comment]
Here's the .gitmodules I used

```
[submodule "cbios"]
        path = msx/cbios
        url = https://github.com/vipoo/cbios.git
        branch = main
[submodule "nextor"]
        path = msx/nextor
        url = https://github.com/vipoo/Nextor.git
        branch = dean/1/v2.1
[submodule "msxsys-build/msxsyssrc"]
        path = msx/msxsys-build/msxsyssrc
        url = https://github.com/vipoo/msxsrcsrc.git
        branch = dean/main
[submodule "referened-repos/MSX-Development"]
        path = referened-repos/MSX-Development
        url = https://github.com/ducasp/MSX-Development.git
[submodule "referened-repos/fusion-c"]
        path = referened-repos/fusion-c
        url = https://github.com/ericb59/Fusion-C-v1.2.git
[submodule "referened-repos/xmodem-1k"]
        path = referened-repos/xmodem-1k
        url = https://github.com/kelvinlawson/xmodem-1k.git
[submodule "msx/apps/chip8"]
        path = msx/apps/chip8
        url = https://github.com/vipoo/rc2014-chip8.git
[submodule "msx/bbcbasic-z80"]
        path = msx/bbcbasic-z80
        url = https://github.com/vipoo/bbcbasic-z80.git
[submodule "referened-repos/msx-hub"]
        path = referened-repos/msx-usb
        url = https://github.com/S0urceror/MSX-USB.git
```

**Comment by vipoo** [comment]
There is a section in the readme for repo clone.  I have added some more notes to help those users who do not wish to setup a ssh key:

-------
Please note: github submodule configuration assumes you are using ssh to access the repos

If you get a permission denied error when attempting to clone the submodules, it may be due to your github access method. The submodules are referenced using git ssh paths (eg: [git@github.com](mailto:git@github.com):vipoo/Nextor.git), as such if you attempt to clone these submodules using only https access, you may get a permission denied error.

To setup github access using ssl - follow the instruction on github at: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Force use of https://... git paths
Alternatively, if you wish to clone using the https path, you may find running this command first before cloning the submodule will help:

git config --global url."https://github.com/".insteadOf git@github.com:
